"""
Visualization coordination module
Coordinates all visualization generation for BioStructBenchmark
"""

from pathlib import Path
from typing import Dict, Optional


def generate_visualizations(results: Dict, output_dir: Path, args) -> Optional[Dict]:
    """Generate all requested visualizations"""
    try:
        from biostructbenchmark.visualization.residue_plots import create_residue_analysis, ResidueVisualizer
        
        if not args.quiet:
            print("  → Generating visualizations...")
        
        viz_results = {}
        viz_dir = output_dir / "visualizations"
        viz_dir.mkdir(exist_ok=True)
        
        # Extract residue data for visualization
        residue_data = None
        analysis_data = {}
        
        # Get residue RMSD data from different result types
        if 'multi_frame' in results and results['multi_frame']:
            # Multi-frame results - we need to access the actual result object
            # This needs to be passed differently from the pipeline
            pass
        elif 'rmsd' in results and results['rmsd'] and results['rmsd'].get('residue_rmsds'):
            # Single RMSD analysis - extract residue data
            residue_data = results['rmsd']['residue_rmsds']
            if not args.quiet:
                print(f"  ✓ Found {len(residue_data)} residues for detailed visualization")
        
        # Generate comprehensive residue analysis if we have residue data
        if residue_data:
            try:
                viz_paths = create_residue_analysis(residue_data, viz_dir, analysis_data)
                viz_results.update(viz_paths)
                
                if not args.quiet:
                    print(f"  ✓ Generated {len(viz_paths)} detailed residue visualizations")
                    
            except Exception as e:
                if not args.quiet:
                    print(f"  ⚠ Detailed residue visualization failed: {e}")
                if args.verbose:
                    import traceback
                    traceback.print_exc()
        else:
            # Fallback message
            if any('rmsd' in str(k).lower() for k in results.keys()):
                if not args.quiet:
                    print("  ℹ RMSD data detected but detailed residue data not available")
                    print("  ℹ Run with updated pipeline for detailed visualizations")
        
        # B-factor data for correlations
        if 'bfactor' in results and results['bfactor']:
            analysis_data['bfactor'] = results['bfactor']
        
        # Consensus data
        if 'consensus' in results and results['consensus']:
            analysis_data['consensus'] = results['consensus']
        
        # Mutation data
        if 'mutations' in results and results['mutations']:
            analysis_data['mutations'] = results['mutations']
        
        # Hydrogen bond data
        if 'hbond' in results and results['hbond']:
            analysis_data['hbond'] = results['hbond']
        
        # Mutant PCA data - visualizations already generated by pipeline
        if 'mutant_pca' in results and results['mutant_pca']:
            mutant_pca_result = results['mutant_pca']
            if mutant_pca_result.get('success'):
                viz_results.update({
                    'mutant_pca_scatter': str(output_dir / "mutant_pca_analysis" / "pca_scatter_plot.png"),
                    'mutant_pca_hotspots': str(output_dir / "mutant_pca_analysis" / "top_residues_pc1_loading.png"),
                    'mutant_pca_data': str(output_dir / "mutant_pca_analysis" / "error_hotspots.csv")
                })
                if not args.quiet:
                    print(f"  ✓ Mutant PCA visualizations available in mutant_pca_analysis/")
            elif not args.quiet:
                print(f"  ⚠ Mutant PCA analysis failed - no visualizations generated")
        
        # Generate basic summary if we have any data
        if results:
            try:
                # Create a simple summary plot instead of complex dashboard
                import matplotlib.pyplot as plt
                fig, ax = plt.subplots(figsize=(10, 6))
                
                # Create summary of available analyses
                analysis_types = list(results.keys())
                analysis_types = [t for t in analysis_types if t != 'visualization']
                
                ax.text(0.1, 0.8, 'BioStructBenchmark Analysis Summary', 
                       fontsize=16, fontweight='bold', transform=ax.transAxes)
                
                y_pos = 0.6
                for i, analysis_type in enumerate(analysis_types):
                    if results[analysis_type]:
                        ax.text(0.1, y_pos - i*0.1, f"✓ {analysis_type.upper()} analysis completed", 
                               fontsize=12, transform=ax.transAxes)
                    else:
                        ax.text(0.1, y_pos - i*0.1, f"✗ {analysis_type.upper()} analysis failed", 
                               fontsize=12, color='red', transform=ax.transAxes)
                
                ax.text(0.1, 0.2, 'Note: Detailed residue visualizations require --save-residue-data flag', 
                       fontsize=10, style='italic', transform=ax.transAxes)
                
                ax.set_xlim(0, 1)
                ax.set_ylim(0, 1)
                ax.axis('off')
                
                summary_path = viz_dir / "analysis_summary.png"
                fig.savefig(summary_path, dpi=300, bbox_inches='tight', facecolor='white')
                plt.close(fig)
                
                viz_results['summary'] = str(summary_path)
                
            except Exception as e:
                if args.verbose:
                    print(f"  ⚠ Could not create summary visualization: {e}")
        
        if not args.quiet:
            if viz_results:
                print(f"  ✓ Generated {len(viz_results)} visualization(s)")
            else:
                print("  ℹ No visualizations generated - detailed data needed")
        
        return viz_results
        
    except ImportError:
        if args.verbose:
            print("  ⚠ Visualization module not available")
        return None
    except Exception as e:
        print(f"  ✗ Visualization failed: {e}")
        if args.verbose:
            import traceback
            traceback.print_exc()
        return None